### ISSUE TITLE
Update to Swift 3

### ISSUE THREAD

**Issue by moritzsternemann** [moritzsternemann/SwipyCell#1]
The goal is to update the repo to work with Swift 3 and to adopt the cosmetical changes in Swift 3 (e.g. camelCase enum values).

Please drop a comment if you are interested so others know that you are working on this issue.
Have fun coding! 😄

**Comment by felton** [comment]
on it!

**Comment by moritzsternemann** [comment]
Great :)

**Comment by rudedogg** [comment]
@felton If you change your mind let me know; I'll take a stab at it.

**Comment by moritzsternemann** [comment]
Since @serejahh is apparently not working on fixing the PR #2 feel free to give it a shot @felton @rudedogg
