### ISSUE TITLE
Swipe Image with text 

### ISSUE THREAD

**Issue by mohsinalimat** [moritzsternemann/SwipyCell#13]
Hello,

I want to implement swipe image with text. and when image change according to text also change.\ so can you please help me?

Thanks,
Mohsinali Matiya

**Comment by moritzsternemann** [comment]
Hello Mohsinali!

Do you want an UITableViewCell with an image and text inside, or do you want the swipe views to have an image and text inside?

**Comment by mohsinalimat** [comment]
Inside swipe view

**Comment by mohsinalimat** [comment]
r u getting my point?

**Comment by moritzsternemann** [comment]
You can just use any view (labels, custom views, etc..) when calling `setSwipeGesture(_ UIView,....)`
