### ISSUE TITLE
exposure of slidingView subview (swipeView) attribute

### ISSUE THREAD

**Issue by DazChong** [moritzsternemann/SwipyCell#14]
Thanks! It's so easy to subclass and implement without breaking anything.

It would be great if we could reference back to the swipeView and change it within closure.

**Comment by moritzsternemann** [comment]
Hey, thanks for the feature request! That's already on my todo list and I'll implemented it in the next week or so 😄

**Comment by DazChong** [comment]
Thanks! No rush. 

Another thing I try to figuring out is the `SwipyCellConfig.shared`. I try to access it in viewcontroller but error with `shared is inaccessible due to internal protection level`.

It would be good if you update the documentation with more complete example.

Again, appreciate your work!

**Comment by moritzsternemann** [comment]
Alright.. thanks for pointing that out. Will be in the next release as well :)

**Comment by moritzsternemann** [comment]
Sorry for the long delay.
The problem with the internal protection level is actually a bug and is fixed in [v3.1.1](https://github.com/moritzsternemann/SwipyCell/releases/tag/3.1.1).

About your feature request:
In which of the closures do you want to change the swipeView and what would be a situation you need this?

**Comment by DazChong** [comment]
NP, thanks for iron it out.

Well, it will most likely been used on `swipyCellDidFinishSwiping`. For my case it's a starring/bookmark feature, and I have 2 icons to indicate the current status.
- If the cell is not `starred`, swipe will revealed `star-outline` icon.
- After user `starred` it, swipe will then reveal `star-filled` icon.

It's not a very useful feature but it will be nice to have it. I can workaround it with a stack of flags array.

**Comment by moritzsternemann** [comment]
Hey, take a look at the latest release ([3.2.0](https://github.com/moritzsternemann/SwipyCell/releases/tag/3.2.0)) and let me know if this solves your issue! 😃
