### ISSUE TITLE
Selector must be exposed as @objc function

### ISSUE THREAD

**Issue by alexleeelkins** [moritzsternemann/SwipyCell#17]
Line 161 of SwipyCell.swift must be changed to
@objc func handlePanGesture(_ gesture: UIPanGestureRecognizer) {
to support Swift 4

**Comment by moritzsternemann** [comment]
Thanks! Fixed in [v3.3.0](https://github.com/moritzsternemann/SwipyCell/releases/tag/3.3.0)
