### ISSUE TITLE
Why set the cell.contentView.backgroundColor white?

### ISSUE THREAD

**Issue by talisk** [moritzsternemann/SwipyCell#8]
I have a TableView with clear background color contentView. I found that the `contentView.backgroundColor` will be set `UIColor.white` when the `contentView.backgroundColor != nil` and `backgroundColor == UIColor.clear`. So when I swipe the cell there's a white background appeared in above of the cell.

The code is in line 136 `SwipyCell.swift`.

**Comment by moritzsternemann** [comment]
I think I did this to prevent the background from peeking through for some special use case but I couldn't figure out why exactly. 😁 

Removed in [2.0.2](https://github.com/moritzsternemann/SwipyCell/releases/tag/2.0.2)
