### ISSUE TITLE
Inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by niazoff** [moritzsternemann/SwipyCell#9]
Hi thanks @moritzsternemann and any other contributors. I'm trying to access `color1` of the `cell` argument in the delegate but I get an error:

> "'color1' is inaccessible due to 'internal' protection level."

Any help would be appreciated!

![error](https://cloud.githubusercontent.com/assets/3903844/21655384/c5d63b22-d287-11e6-9ed3-8a9dbeacac1f.png)

**Comment by niazoff** [comment]
All that's required is a `public` keyword in the source actually.

**Comment by moritzsternemann** [comment]
Going to look into this tonight, thanks for submitting this Issue!

**Comment by moritzsternemann** [comment]
Fixed in [v2.0.3](https://github.com/moritzsternemann/SwipyCell/releases/tag/2.0.3)
